import type { TemplateMeta } from "@/lib/resume/types";

export const templates = [
  {
    id: "ats",
    name: "ATS-Friendly",
    description: "Single column, standard headings, and easy for application systems to parse.",
    thumbnail: "ats",
    supportsPhoto: false,
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    atsSafe: true,
    fields: {
      headline: true,
      address: false,
      website: true,
      linkedin: false,
      thesis: true,
      coursework: true,
      studyAbroad: false,
      highSchool: false,
      flatSkills: true,
      groupedSkills: false,
    },
  },
  {
    id: "modern",
    name: "Modern Professional",
    description: "A contemporary single-column layout with more breathing room and hierarchy.",
    thumbnail: "modern",
    supportsPhoto: false,
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    atsSafe: true,
    fields: {
      headline: true,
      address: false,
      website: true,
      linkedin: false,
      thesis: true,
      coursework: true,
      studyAbroad: false,
      highSchool: false,
      flatSkills: true,
      groupedSkills: false,
    },
  },
  {
    id: "minimalist",
    name: "Minimalist",
    description: "Only the essentials, with the focus kept firmly on your work.",
    thumbnail: "minimalist",
    supportsPhoto: false,
    sections: ["summary", "experience", "education", "skills"],
    atsSafe: true,
    fields: {
      headline: false,
      address: false,
      website: true,
      linkedin: false,
      thesis: true,
      coursework: true,
      studyAbroad: false,
      highSchool: false,
      flatSkills: true,
      groupedSkills: false,
    },
  },
  {
    id: "harvard",
    name: "Harvard / Traditional",
    description: "A classic conservative layout for law, finance, and academia — centered headers, grouped skills.",
    thumbnail: "harvard",
    supportsPhoto: false,
    sections: ["education", "experience", "leadership", "skills"],
    atsSafe: true,
    fields: {
      headline: false,
      address: true,
      website: false,
      linkedin: false,
      thesis: true,
      coursework: true,
      studyAbroad: true,
      highSchool: true,
      flatSkills: false,
      groupedSkills: true,
    },
  },
  {
    id: "classic-tech",
    name: "Classic Tech",
    description: "The classic single-column engineering resume — compact, link-friendly, and easy for recruiters to scan.",
    thumbnail: "classic-tech",
    supportsPhoto: false,
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    atsSafe: true,
    fields: {
      headline: true,
      address: false,
      website: true,
      linkedin: false,
      thesis: false,
      coursework: false,
      studyAbroad: false,
      highSchool: false,
      flatSkills: true,
      groupedSkills: false,
    },
  },
  {
    id: "awesome-cv",
    name: "Awesome CV",
    description: "A polished, contemporary CV with accent-colored section headers and an optional profile photo.",
    thumbnail: "awesome-cv",
    supportsPhoto: true,
    sections: ["summary", "experience", "education", "skills", "projects", "certifications"],
    atsSafe: false,
    fields: {
      headline: true,
      address: false,
      website: true,
      linkedin: true,
      thesis: false,
      coursework: false,
      studyAbroad: false,
      highSchool: false,
      flatSkills: true,
      groupedSkills: false,
    },
  },
  {
    id: "two-column",
    name: "Two-Column",
    description: "A scannable layout with a sidebar for contact, skills, and an optional photo, next to a focused main column.",
    thumbnail: "two-column",
    supportsPhoto: true,
    sections: ["experience", "education", "skills", "projects", "certifications"],
    atsSafe: false,
    fields: {
      headline: true,
      address: false,
      website: true,
      linkedin: true,
      thesis: false,
      coursework: false,
      studyAbroad: false,
      highSchool: false,
      flatSkills: true,
      groupedSkills: false,
    },
  },
] satisfies TemplateMeta[];

export function getTemplateMeta(templateId: string): TemplateMeta {
  return templates.find((template) => template.id === templateId) ?? templates[0];
}

export function templatesForSections(sections: string[]) {
  const wanted = new Set(sections);
  return templates.filter((template) => template.sections.every((section) => wanted.has(section)));
}